### ISSUE TITLE
Nested c4plantuml Diagrams Failing

### ISSUE THREAD

**Issue by bai-yi-bai** [asciidoctor/asciidoctor-kroki#439]
Hello,

I am new to using code-generated diagrams and am doing testing before rolling this out wider. I am having trouble using 'nested' c4plantuml diagrams with Antora Assembler when it calls asciidoctor-pdf. I am cautious about reporting this issue because I may not have my kroki.io correctly configured. 
For the record, I do not know where/how in Windows to '<1> Register the extension in the global registry' or ' <2> Register the extension in a dedicated registry'.
My asciidoctor gem is 2.0.20, Ruby environment is 3.2.2.

With that said, I believe I have enabled the asciidoctor-kroki extension correctly and I have called the extension in antora assembler with the `-r asciidoctor-kroki` parameter Also note, I am not running bundle.
```
ascidoc:
  extensions:
     - asciidoctor-kroki
```

I am using this [example, 103,](https://github.com/plantuml-stdlib/C4-PlantUML/issues/103#issuecomment-751371430) from the C4-PlantUML issues.
```@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth auto

skinparam Backgroundcolor transparent
skinparam defaultTextAlignment center
rectangle rect1 [
== rect1
..
{{
  rectangle nested1
  rectangle nested2

Container(c1, "Container", "tech", "Some long description of the container.\n You have to use new line characters\n in order to keep the layout")
}}
]
rectangle rect2

rect1 -r-> rect2
@enduml
```

### Results
- Microsoft Visual Studio Code AsciiDoc extension preview: displays correctly
- Microsoft Visual Studio Code AsciiDoc extension html: displays correctly
- Microsoft Visual Studio Code AsciiDoc extension pdf: only displays the code, not the image
- Antora HTML: Broken SVG icon; 
- When I try to visit the URL in Antora's HTML output, I get a URI is too long message; it seems to be 17,000 characters; covered by this issue: [398](https://github.com/asciidoctor/asciidoctor-kroki/issues/398)
- Antora Assembler AsciiDoctor-PDF:  When it runs, I get this error in the console
```
Error retrieving URL data:image/svg+xml;base64,<truncated characters>==: prawn-svg only supports base64-encoded image/png and image/jpg data URLs.
```
- The PDF only shows the rec1, and rect2 content, the nested content does not appear.

I also tried both `kroki-http-method` `post` and `adaptive` but received the same result.

I'd be grateful for any feedback

**Comment by ggrossetie** [comment]
> Microsoft Visual Studio Code AsciiDoc extension pdf: only displays the code, not the image

You probably need to load the Ruby extension when converting to PDF using `-r asciidoctor-kroki` (please note that the gem should be available).

> Antora HTML: Broken SVG icon; When I try to visit the URL in Antora's HTML output, I get a URI is too long message; it seems to be 17,000 characters...

That's correct, please read: https://docs.kroki.io/kroki/setup/configuration/#_max_uri_length
You should use `kroki-fetch-diagram` in Antora to retrieve the image from the remote server (otherwise you will rely on https://kroki.io or your remote server when viewing your documentation site)

> Antora Assembler AsciiDoctor-PDF: When it runs, I get this error in the console


I guess `prawn-svg` does not support base64 encoded SVG

```
Error retrieving URL data:image/svg+xml;base64,<truncated characters>==: prawn-svg only supports base64-encoded image/png and image/jpg data URLs.
```

You might want to use png or jpg when using Asciidoctor PDF.


> Nested c4plantuml Diagrams Failing

I don't see how this is related to the issue you are describing?

In the future, please use the community chat https://chat.asciidoctor.org if you need support. The issue tracker is used for verifiable bugs and formal change requests.

Thanks!
